### PR TITLE
Replace Travis with Github Actions

### PR DESCRIPTION
**Pull request by LexiconCode**

### CODE REVIEW

**Comment by LexiconCode** [comment]
Fails during castervoice package install due to post install script.

**Comment by LexiconCode** [comment]
A bug [cannot push from local changes](https://stackoverflow.com/questions/56600686/can-i-edit-the-main-workflow-github-actions-file-locally)

**Comment by kendonB** [comment]
Travis is on the way out soon https://ropensci.org/technotes/2020/11/19/moving-away-travis/

We should try and transition to GA soon

**Comment by LexiconCode** [comment]
@kendonB okay I've clean this up a bit. 
The last hurdle is getting Tkinter to behave nicely on Linux Ubuntu. Any thoughts?
https://github.com/LexiconCode/Caster/pull/11/checks?check_run_id=1445481380

Once we are done I will probably close out this branch and create a new one for PR upstream.

```
    pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.6/x64/lib
************* Module castervoice.asynch.mouse.grids
castervoice/asynch/mouse/grids.py:13:4: E0401: Unable to import 'Tkinter' (import-error)
************* Module castervoice.asynch.hmc.hmc_ask_directory
castervoice/asynch/hmc/hmc_ask_directory.py:3:4: E0401: Unable to import 'Tkinter' (import-error)
************* Module castervoice.asynch.hmc.homunculus
castervoice/asynch/hmc/homunculus.py:5:4: E0401: Unable to import 'Tkinter' (import-error)
castervoice/asynch/hmc/homunculus.py:6:4: E0401: Unable to import 'Tkinter' (import-error)
************* Module castervoice.asynch.hmc.hmc_recording
castervoice/asynch/hmc/hmc_recording.py:6:4: E0401: Unable to import 'Tkinter' (import-error)
castervoice/asynch/hmc/hmc_recording.py:7:4: E0401: Unable to import 'Tkinter' (import-error)
************* Module castervoice.asynch.hmc.hmc_confirm
castervoice/asynch/hmc/hmc_confirm.py:3:4: E0401: Unable to import 'Tkinter' (import-error)
************* Module castervoice.lib.merge.state.stack
castervoice/lib/merge/state/stack.py:8:4: E0401: Unable to import 'Queue' (import-error)
```

**Comment by kendonB** [comment]
I'm guessing pylint is running as the 2.7 version

**Comment by kendonB** [comment]
No issues locally:

```
kendonb@kendonb-VirtualBox:~/Caster$ git status
On branch GithubActions
Your branch is up to date with 'origin/GithubActions'.

nothing to commit, working tree clean
kendonb@kendonb-VirtualBox:~/Caster$ pylint --version
pylint 2.4.4
astroid 2.3.3
Python 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
kendonb@kendonb-VirtualBox:~/Caster$ pylint -E _caster.py 
kendonb@kendonb-VirtualBox:~/Caster$ 
```

**Comment by LexiconCode** [comment]
I can confirm it's using the correct version of Python

```
2020-11-25T19:11:46.1984123Z ##[group]Run pylint -E _caster.py
2020-11-25T19:11:46.1984870Z [36;1mpylint -E _caster.py[0m
2020-11-25T19:11:46.1985365Z [36;1mpylint -E castervoice[0m
2020-11-25T19:11:46.2028284Z shell: /usr/bin/bash -e {0}
2020-11-25T19:11:46.2028735Z env:
2020-11-25T19:11:46.2029396Z   pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
2020-11-25T19:11:46.2031490Z   LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.6/x64/lib
2020-11-25T19:11:46.2032371Z ##[endgroup]
2020-11-25T19:12:31.8751247Z ************* Module castervoice.asynch.mouse.grids
2020-11-25T19:12:31.8756907Z castervoice/asynch/mouse/grids.py:13:4: E0401: Unable to import 'Tkinter' (import-error)
2020-11-25T19:12:31.8758114Z ************* Module castervoice.asynch.hmc.hmc_ask_directory
2020-11-25T19:12:31.8759477Z castervoice/asynch/hmc/hmc_ask_directory.py:3:4: E0401: Unable to import 'Tkinter' (import-error)
2020-11-25T19:12:31.8760512Z ************* Module castervoice.asynch.hmc.homunculus
2020-11-25T19:12:31.8761851Z castervoice/asynch/hmc/homunculus.py:5:4: E0401: Unable to import 'Tkinter' (import-error)
2020-11-25T19:12:31.8763126Z castervoice/asynch/hmc/homunculus.py:6:4: E0401: Unable to import 'Tkinter' (import-error)
2020-11-25T19:12:31.8764099Z ************* Module castervoice.asynch.hmc.hmc_recording
2020-11-25T19:12:31.8765271Z castervoice/asynch/hmc/hmc_recording.py:6:4: E0401: Unable to import 'Tkinter' (import-error)
2020-11-25T19:12:31.8766521Z castervoice/asynch/hmc/hmc_recording.py:7:4: E0401: Unable to import 'Tkinter' (import-error)
2020-11-25T19:12:31.8767474Z ************* Module castervoice.asynch.hmc.hmc_confirm
2020-11-25T19:12:31.8768627Z castervoice/asynch/hmc/hmc_confirm.py:3:4: E0401: Unable to import 'Tkinter' (import-error)
2020-11-25T19:12:31.8769626Z ************* Module castervoice.lib.merge.state.stack
2020-11-25T19:12:31.8770920Z castervoice/lib/merge/state/stack.py:8:4: E0401: Unable to import 'Queue' (import-error)
2020-11-25T19:12:34.7549010Z ##[error]Process completed with exit code 2.
2020-11-25T19:12:34.7674392Z Post job cleanup.
2020-11-25T19:12:34.8822975Z [command]/usr/bin/git version
```

https://pipelines.actions.githubusercontent.com/wJdnu8OTskDLo4hnuArb285mn9KhkvMemPWAGsJVSQdaMPxa1B/_apis/pipelines/1/runs/48/signedlogcontent/8?urlExpires=2020-11-25T19%3A14%3A42.5891847Z&urlSigningMethod=HMACV1&urlSignature=mpzlUP1JqtdJ4bG%2BYLeslSAm%2F3j8e%2BSkBaROJEGC1n8%3D

**Comment by LexiconCode** [comment]
I don't care for the workaround but basically I used `# pylint: disable=import-error` to get around the errors. It does not solve the underlying issue.

**Comment by LexiconCode** [comment]
As it turns out this is more of an issue not with how TK is installed but how pylint seems to be inconsistent across platforms on github actions. Tested with the file below and a stripped-down version of above and a clean repo. Results as follows

https://0bin.net/paste/sGbbX84r#vxpe73nMg6-YHd+Y+Z+hqCl8YRh9a8pmzgMK01PfWeF

python 2 windows (2.7.x) Fail
python 3 windows (3.8.x) Success
python 3 linux (3.8.x) Fail
python 3 MacOs (3.8.x)  Success

tk_test.py
```python
import sys, six
print(sys.version)

if six.PY2:
    import Tkinter as tk
else:
    import tkinter as tk

print(tk.TkVersion) # succeeds in all platforms to print version number
```
Any thoughts besides disabling pylint imports?

**Comment by LexiconCode** [comment]
Summary I found the document issue on `conditional import against six.PY2 emits error` on https://github.com/PyCQA/pylint

**Test case 1**
Results as follows:

- python 2 windows (2.7.x) Linting Fail 
E:  7, 4: Unable to import 'tkinter' (import-error)

- python 3 windows (3.8.x) Success Linting

- python 3 linux (3.8.x) Linting Fail 
E:  7, 4: Unable to import 'tkinter' (import-error)

- python 3 MacOs (3.8.x)  Success Linting

**Test Case 1**
tk_test.py
```python
import sys, six
print(sys.version)

if six.PY2:
    import Tkinter as tk
else:
    import tkinter as tk

print(tk.TkVersion) # succeeds in all platforms to print version number
```

**Test Case 2**
Results as follows:
- Success on all platforms

```python
import sys, six
print(sys.version)

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

print(tk.TkVersion)
```

Github Actions Configuration for both tests
https://0bin.net/paste/sGbbX84r#vxpe73nMg6-YHd+Y+Z+hqCl8YRh9a8pmzgMK01PfWeF
```
    name: Python tk package
     
    on: [push]
     
    jobs:
      python-windows-2-7:
            name: python 2 windows
            runs-on: windows-latest
            strategy:
              matrix:
                python-version: [2.7.x]
            steps:
              - uses: actions/checkout@v2
              - name: Set up Python
                uses: actions/setup-python@v2
                with:
                  python-version: ${{ matrix.python-version }}
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install --upgrade setuptools
                  pip install six 
                  pip install pylint 
              - name: Run tk_test.py
                run: |
                  python tk_test.py
              - name: Lint with pylint
                run: |
                  pylint -E tk_test.py
      python-windows-3-8-x:
            name: python 3 windows
            runs-on: windows-latest
            strategy:
              matrix:
                python-version: [3.8.x]
            steps:
              - uses: actions/checkout@v2
              - name: Set up Python
                uses: actions/setup-python@v2
                with:
                  python-version: ${{ matrix.python-version }}
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install --upgrade setuptools
                  pip install six
                  pip install pylint 
              - name: Lint with pylint
                run: |
                  pylint -E tk_test.py
      python-linux-3-8-x:
            name: python 3 linux
            runs-on: ubuntu-20.04
            strategy:
              matrix:
                python-version: [3.8.x]
            steps:
              - uses: actions/checkout@v2
              - name: Set up Python
                uses: actions/setup-python@v2
                with:
                  python-version: ${{ matrix.python-version }}
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install --upgrade setuptools
                  pip install six
                  pip install pylint 
              - name: Run tk_test.py
                run: |
                  python tk_test.py
              - name: Lint with pylint
                run: |
                  pylint -E tk_test.py
      python-macos-3-8-x:
            name: python 3 MacOs
            runs-on: macos-latest
            strategy:
              matrix:
                python-version: [3.8.x]
            steps:
              - uses: actions/checkout@v2
              - name: Set up Python
                uses: actions/setup-python@v2
                with:
                  python-version: ${{ matrix.python-version }}
              - name: Install dependencies
                run: |
                  python -m pip install --upgrade pip
                  pip install --upgrade setuptools
                  pip install six
                  pip install pylint 
              - name: Run tk_test.py
                run: |
                  python tk_test.py
              - name: Lint with pylint
                run: |
                  pylint -E tk_test.py
```

**Comment by LexiconCode** [comment]
So it means either doing a `try/except ImportError:` or disabling pylint error messages via `disabling # pylint: disable=import-error`

**Pull request closed without merging**
